module.exports = {
	'Arcanist Boots': '16800',
	'Felheart Gloves': '16805',
	'Cenarion Boots': '16829',
	'Lawbringer Boots': '16859',
	'Gauntlets of Might': '16863',
	'Choker of Enlightenment': '17109',
	'Helm of the Lifegiver': '18870',
	'Robe of Volatile Power': '19145',
	'Wristguards of Stability': '19146',
	'Manastorm Leggings': '18872',
	'Salamander Scale Pants': '18875',
	'Heavy Dark Iron Ring': '18879',
	'Ring of Spell Power': '19147',
	'Pants of Prophecy': '16814',
	'Arcanist Leggings': '16796',
	'Felheart Pants': '16810',
	'Giantstalkers Leggings': '16847',
	'Lawbringer Legplates': '16855',
	'Legplates of Might': '16867',
	'Medallion of Steadfast Might': '',
	'Strikers Mark': '',
	'Earthshaker': '',
	'Eskhanders Right Claw': '',
	'Flameguard Gauntlets': '',
	'Mana Igniting Cord': '',
	'Quick Strike Ring': '',
	'Talisman of Ephemeral Power': '',
	'Fire Runed Grimoire': '',
	'Obsidian Edged Blade': '',
	'Gloves of Prophecy': '',
	'Nightslayer Gloves': '',
	'Giantstalkers Boots': '',
	'Lawbringer Gauntlets': '',
	'Sabatons of Might': '',
	'Bindings of the Windseeker': 'spell_ice_lament',
	'Arcanist Crown': '',
	'Felheart Horns': '',
	'Nightslayer Cover': '',
	'Giantstalkers Helmet': '',
	'Lawbringer Helm': '',
	'Helm of Might': '',
	'Drillborer Disk': '',
	'Aurastone Hammer': '',
	'Brutality Blade': '',
	'Arcanist Mantle': '',
	'Felheart Shoulder Pads': '',
	'Lawbringer Spaulders': '',
	'Seal of the Archmagus': '',
	'Boots of Prophecy': '',
	'Arcanist Gloves': '',
	'Felheart Slippers': '',
	'Nightslayer Boots': '',
	'Giantstalkers Gloves': '',
	'Mantle of Prophecy': '',
	'Nightslayer Shoulder Pads': '',
	'Giantstalkers Epaulets': '',
	'Pauldrons of Might': '',
	'Robes of Prophecy': '',
	'Arcanist Robes': '',
	'Felheart Robes': '',
	'Nightslayer Chestpiece': '',
	'Cenarion Vestments': '',
	'Giantstalkers Breastplate': '',
	'Lawbringer Chestguard': '',
	'Breastplate of Might': '',
	'Blastershot Launcher': '',
	'Azuresong Mageblade': '',
	'Staff of Dominance': '',
	'Wild Growth Spaulders': '',
	'Sash of Wispering Secrets': '',
	'Wristguards of True Flight': '',
	'Cauterizing Band': '',
	'Core Hound Tooth': '',
	'Ancient Petrified Leaf': 'spell_nature_resistnature',
	'The Eye of Divinity': 'spell_holy_mindsooth',
	'Eye of Sulfuras': '',
	'Leggings of Transcendence': '',
	'Netherwind Pants': '',
	'Nemesis Leggings': '',
	'Bloodfang Pants': '',
	'Dragonstalkers Legguards': '',
	'Judement Legplates': '',
	'Legplates of Wrath': '',
	'Crown of Destuction': '',
	'Choker of the Firelord': '',
	'Cloak of the Shrouded Mists': '',
	'Dragons Blood Cape': '',
	'Onslaught Girlde': '',
	'Band of Accuria': '',
	'Malistars Defender': '',
	'Perditions Blade': '',
	'Spinal Reaper': '',
	'Bonereavers Edge': '',
	'Girdle of Prophecy': '',
	'Arcanist Belt': '',
	'Nightslayer Belt': '',
	'Lawbringer Belt': '',
	'Belt of Might': '',
	'Vambraces of Prophecy': '',
	'Arcanist Bindings': '',
	'Felheart Bracers': '',
	'Lawbringer Bracers': '',
	'Bracers of Might': '',
	'Halo Of Transcendence': '',
	'Netherwind Crown': '',
	'Nemesis Skullcap': '',
	'Bloodfang Hood': '',
	'Stormrage Cover': '',
	'Dragonstalkers Helm': '',
	'Judgement Crown': '',
	'Helm of Wrath': '',
	'Head of Onyxia': '',
	'Sapphiron Drape': '',
	'Ring of Binding': '',
	'Shard of the Scale': '',
	'Ancient Cornerstone Grimoire': '',
	'Deathbringer': '',
	'Viskag the Bloodletter': ''
};
